  unless Vagrant.has_plugin?("vagrant-disksize")
    raise  Vagrant::Errors::VagrantError.new, "vagrant-disksize plugin is missing. Please install it using 'vagrant plugin install vagrant-disksize' and rerun 'vagrant up'"
  end
  
  Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/bionic64"

    config.vm.network :private_network, ip: '10.47.43.12'

    config.vm.synced_folder "../../../../installers", "/tmp/cx"
    
     config.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "8192"
      vb.cpus = 4
      vb.name = "cxcomm"
    end

    config.vm.provision "chef_zero" do |chef|
      chef.channel = "stable"
      chef.version = "15.1.36"
      chef.nodes_path = "~/chef-base/nodes"
      chef.cookbooks_path = "../../chef/cookbooks"
      chef.custom_config_path = "CustomConfiguration.chef"
      
      chef.log_level = "info"
      chef.roles_path = "../../chef/roles"
      chef.add_role("cxcomm")
    end

  end